spring:
  application:
    name: ai-codegen
  redis:
    enabled: false
  session:
    store-type: none # redis, none
    timeout: 259200
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_codegen
    username: root
    password: "0406"
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      ttl: 3600 # 缓存过期时间
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
springdoc:
  group-configs:
    - group: "default"
      paths-to-match: "/**"
      packages-to-scan: com.github.tianchenghang.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: https://platform.deepseek.com/api_keys
      model-name: deepseek-chat
      # strict-json-schema: true
      # response-format: json_object
      max-tokens: 8192
      log-requests: true
      log-responses: true
      max-retries: 3
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: https://platform.deepseek.com/api_keys
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: https://platform.deepseek.com/api_keys
      model-name: deepseek-reasoner
      max-tokens: 8192
      temperature: 0.1
      log-requests: true
      log-responses: true
    route-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: https://bailian.console.aliyun.com/cn-beijing/?tab=model#/api-key
      model-name: qwen-turbo
      max-tokens: 100
      log-requests: true
      log-responses: true
storage:
  local:
    path: ./uploads
    base-url: http://localhost:8123/api/static
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
codegen:
  deploy-host: http://localhost/dist
